# action.yml
name: 'Check for secrects'
description: 'Check for security vulnerabilities'
outputs:
  result: # id of output
    description: 'Scan results'
runs:
  using: 'docker'
  image: 'Dockerfile'