on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Check for secrets
        id: secrets-check
        uses: maddygoround/secrets-not-allowed@main
        with:
          workspace: ${{ github.workspace }}
      - name: Get results of scan
        run: echo "The time was ${{ steps.hello.outputs.result }}"