on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Vulnerabilities checks
    steps:
      - name: Check for secrets
        id: secrets-check
        uses: maddygoround/secrets-not-allowed@main
        with:
          workspace: ${{ github.workspace }}
      - name: Get results of scan
        run: echo "Scan Results - ${{ steps.hello.outputs.result }}"